---
fontsize: 12pt
lang: spanish
mainlang: spanish
other_langs:
    -   english
papersize: letterpaper
documentclass: report
geometry:
    -   inner=4cm
    -   outer=3cm
    -   vmargin=3cm
    -   twoside
mainfont: Times New Roman
institution: Universidad Técnica Federico Santa María
academic_unit: Departamento de Jirafología
city: Valparaíso
country: Chile
title: Ergonomía de Jirafas
author: Períco Pérez Palotes
degree: Ingeniero Civil de Jirafas Levitantes
professor: Juan Josefo Jara Jote
month: Enero
year: 2015
advertencia: true
numbersections: true
toc-depth: 1
agradecimientos: src/preambulo/agradecimientos.tex
dedicatoria: src/preambulo/dedicatoria.tex
resumen: src/preambulo/resumen.tex
abstract: src/preambulo/abstract.tex
definiciones: src/definiciones
bibliografia: src/bibliografia.tex
main_content:
    -   src/1-introduccion/introduccion.tex
    -   src/2-estado-del-arte/estado-del-arte.tex
    -   src/3-propuesta/propuesta.tex
    -   src/4-resultados/resultados.tex
    -   src/5-conclusiones/conclusiones.tex
anexos:
    -   src/anexos/anexoA.tex
...
